POST http://localhost:3333/auth/signup
content-type: application/json

{
  "email": "test2@test.com",
  "password": "asdfasdf"
}

# GET http://localhost:3333/auth/1
# content-type: application/json

# ## FIND ALL USERS WITH EMAIL
# GET http://localhost:3333/auth

### DELETE USER WITH GIVEN ID
# DELETE http://localhost:3333/auth/2

### UPDATE USER WITH GIVEN ID
# PATCH http://localhost:3333/auth/1
# content-type: application/json

# {
#   "email": "test@test.com"
# }
